// Generated by Wrangler on Thu Nov 28 2024 03:31:54 GMT+0330 (Iran Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
